@echo off
echo Starting Bread Distribution System...
call .\venv\Scripts\activate
echo Installing dependencies...
pip install -r requirements.txt
echo Starting Streamlit server...
streamlit run app.py
pause 